name: Build and Deploy
on: [push]
jobs:
    generate-report:
        runs-on: ubuntu-latest
        steps:
            - name: generator
              run: dotnet test --collect:"XPlat Code Coverage" added to git action