name: Build and Deploy
on: [push]
jobs:
    generate-report:
        runs-on: ubuntu-latest
        steps:
            - name: generator
            - run: ls
            - run: cd /tests/Calculator.Test && dotnet test --collect:"XPlat Code Coverage"