name: Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    generate-report:
        runs-on: ubuntu-latest
        steps:
            - name: generator
              uses: dotnet test --collect:"XPlat Code Coverage" added to git action